title: "Especialistas en Salud Mental y Neurología por 100.000 Habit"
description: "Base de datos longitudinal (2000-2026) sobre la densidad de especialistas en salud mental y neurología por cada 100.000 habitantes en 16 países iberoa"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/especialistas-en-salud-mental-y-neurologia-por-100000-habitantes-en-iberoamerica"
