# Jekyll configuration for GitHub Pages
title: "especialistas-en-salud-mental-y-neurologia-por-100000-habitantes-en-iberoamerica"
description: "Base de datos longitudinal (2000-2026) sobre la densidad de especialistas en salud mental y neurología por cada 100.000 habitantes en 16 países iberoamericanos, incluyendo promedios OCDE y ALC. Variables: psiquiatras, psicólogos clínicos, neurólogos,"
url: "https://juanmoisesd.github.io"
baseurl: "/especialistas-en-salud-mental-y-neurologia-por-100000-habitantes-en-iberoamerica"

author:
  name: "Juan Moisés de la Serna Tuya"
  orcid: "0000-0002-8401-8018"
  linkedin: "https://www.linkedin.com/in/juanmoisesdelaserna/"
  scopus: "26632846700"
  institution: "Universidad Internacional de La Rioja (UNIR)"
  email: "juanmoises.delaserna@unir.net"

# SEO
tagline: "Open Research Dataset"
lang: "en"

# Social
twitter:
  username: juanmoisesd
  card: summary

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Build
theme: minima
include:
  - README.md
  - GLOSSARY.md
  - ABOUT_THE_AUTHOR.md
  - CITATION_GUIDE.md

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
